allowBuilds:
  argon2: true
  esbuild: true
  hexagonal-payments-core: true
  hexagonal-payments-core@git+https://github.com/jesusuzcategui/hexagonal-payments-core.git#1a83f26eafe08c405c09013b8e392cda44b6e274: true
